// action types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PHRASES = 'SET_PHRASES';
export const SET_LANGUAGE_NAME = 'SET_LANGUAGE_NAME';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_LEARNT_PHRASES = 'SET_LEARNT_PHRASES';
export const SHOW_LEARNT_PHRASES = 'SHOW_LEARNT_PHRASES';
export const STORE_LEARNT_PHRASES = 'STORE_LEARNT_PHRASES';
