// action types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PHRASES = 'SET_PHRASES';
export const SET_LANGUAGE_NAME = 'SET_LANGUAGE_NAME';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_NEW_TERMS = 'SET_NEW_TERMS';
export const SET_SEEN_PHRASE = 'SET_SEEN_PHRASE';
export const REMOVE_FROM_SEEN_PHRASES = 'REMOVE_FROM_SEEN_PHRASES';

