 // action types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PHRASES = 'SET_PHRASES';
export const SET_LANGUAGE_NAME = 'SET_LANGUAGE_NAME';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_LEARNT_PHRASES = 'SET_LEARNT_PHRASES';
